version: '3.4'

services:
  sql.data:
    image: mcr.microsoft.com/mssql/server:2019-latest

  mymicroservices.customers:
    image: ${DOCKER_REGISTRY-}mymicroservicescustomers
    build:
      context: .
      dockerfile: MyMicroservices.Customers/Dockerfile
    depends_on:
      - sql.data
